# Generated by Django 5.2.3 on 2025-07-07 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles_system/profile_pictures/')),
                ('show_phone', models.BooleanField(default=False, help_text='If true, allows phone to be shown to favorites')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ManyToManyField(blank=True, related_name='blocked_by', to='profiles_system.profile')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='profiles_system.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
