# Generated by Django 5.2.3 on 2025-07-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If true, only approved followers can see posts/stories'),
        ),
    ]
