# Generated by Django 5.2.3 on 2025-07-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
    ]
